api_key = ""
model="gpt-3.5-turbo-1106"
output_path="./output.txt"
max_tokens=4096
prompt="""
Please, describe the following as much as possible. Include the business name and profile.
"""
[[messages]]
role = "system"
content = '''
# MISSION
You are a Sparse Priming Representation (SPR) writer. An SPR is a particular kind of use of language for advanced NLP, NLU, and NLG tasks, particularly useful for the latest generation of Large Language Models (LLMs). You will be given information by the USER which you are to render as an SPR.

# THEORY
LLMs are a kind of deep neural network. They have been demonstrated to embed knowledge, abilities, and concepts, ranging from reasoning to planning, and even to theory of mind. These are called latent abilities and latent content, collectively referred to as latent space. The latent space of an LLM can be activated with the correct series of words as inputs, which will create a useful internal state of the neural network. This is not unlike how the right shorthand cues can prime a human mind to think in a certain way. Like human minds, LLMs are associative, meaning you only need to use the correct associations to "prime" another model to think in the same way.

# METHODOLOGY
Render the input as a distilled list of succinct statements, assertions, associations, concepts, analogies, and metaphors. The idea is to capture as much, conceptually, as possible but with as few words as possible. Write it in a way that makes sense to you, as the future audience will be another language model, not a human.
'''

[[messages]]
role = "user"
content = "We are interested only on features to create a customer profile."

[[filters]]
  [[filters.messages]]
  role = "user"
  content = '''
  # Business one #
  - Tony Gonzalez: Leader, web retail wizard team.
- Custom Shopify apps: Specialization, merchant focused.

# End business one #

# Business two #

{prevResponse}

# End business two #

Please, use the information of # business one # and # business two # and find potential synergies and areas of opportinity for those business.
  '''


[[filters]]
  [[filters.messages]]
  role="user"
  content="Summarize all the information you have provided so far."  

[[filters]]
  [[filters.messages]]
  role = "user"
  content = '''
  Take the information of your last response and create a compelling sales letter. 
  We need you to switch to creative writing.
  Act on behalf of Tony Gonzalez and act as them wanting to start a parnetship with the other business.
  Our CTA is having a meeting to explore potential parternships together

  '''

[[filters]]
  [[filters.messages]]
  role = "user"
  content = '''
  Make the following letter more natural, less salesly, more human, more casual!:
  
  
  {prevResponse}
  
  Make the previous letter more natural, less salesly, more human, more casual!
  REPEAT, AVOID USING SALES LANGUAGE YOU NEED TO ACT AS A HUMAN AND MAKE IT CASUAL.
  '''
  

[[filters]]
  [[filters.messages]]
  role = "user"
  content = '''  
  Keep it casual and human, natural.  
  REPEAT, AVOID USING SALES LANGUAGE YOU NEED TO ACT AS A HUMAN AND MAKE IT CASUAL.
  Reduce the size of your the following letter to max 200 words.  
  Keep the core information in it. Wipe out all the uneccesary fluff and keep the core only.
  Reduce the size of your the following letter to max 200 words!  

  {prevResponse}

  '''


[[filters]]
  [[filters.messages]]
  role = "user"
  content = '''
  REMOVE ALL PLACEHOLDERS!
  REMOVE ALL PLACEHOLDERS!
  REMOVE ALL PLACEHOLDERS!
  Keep all the text as it is except for the placeholders!  
  {prevResponse}
  '''
  



