api_key = "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"
model="gpt-3.5-turbo-1106"
output_path="./output.txt"
max_tokens=1000
prompt="""
Can you explain what is this?
"""
[[messages]]
role = "system"
content = "You are a helpful assistant"
[[messages]]
role = "user"
content = "Please, act as a pirate"

